name: Pull Request SBOM Scan

on:
  pull_request:
    branches:
        - master

jobs:
    sbom:
        runs-on: ubuntu-latest
        steps:
        - name: Generate SBOM
          uses: anchore/sbom-action@v0
          with:
            artifact-name: asciify.pr.spdx.json
            file: go.mod
    analyze:
        needs: sbom
        outputs:
            result: ${{steps.analysis.outputs.result}}
        runs-on: ubuntu-latest
        steps:
        - name: Download SBOM
          uses: actions/download-artifact@v4
          with:
            name: asciify.pr.spdx.json
        - name: Setup Grype
          uses: anchore/scan-action/download-grype@v3
          id: grype
        - name: Analyze SBOM
          run: ${{steps.grype.outputs.cmd}} sbom:asciify.pr.spdx.json -o table --file analysis.out
          id: analysis
        - name: Save Analysis
          uses: actions/upload-artifact@v4
          with:
            name: analysis.out
            path: analysis.out
    comment:
        needs: analyze
        runs-on: ubuntu-latest
        steps:
        - name: Download Analysis Results
          uses: actions/download-artifact@v4
          with:
            name: analysis.out
        - name: Comment on PR
          uses: actions/github-script@v6
          with:
            script: |
              const fs = require('fs')
              const analysisText = fs.readFileSync("analysis.out", { encoding: "utf8" })
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "```" + analysisText + "```"
              })
