name: Pull Request SBOM Scan

on:
  pull_request:
    branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the Code
          uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21.x'
        - name: Build
          id: build_binary
          run: go build -v -o asciify asciify.go
        - name: Save Artifact
          uses: actions/upload-artifact@v4
          with:
            name: pr-build
            path: asciify
    sbom:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download Build
          uses: actions/download-artifact@v4
          with:
            name: pr-build
        - name: Generate SBOM
          uses: anchore/sbom-action@v0
          with:
            artifact-name: asciify.pr.spdx.json
            file: asciify
    analyze:
        needs: sbom
        outputs:
            result: ${{steps.analysis.outputs.result}}
        runs-on: ubuntu-latest
        steps:
        - name: Download SBOM
          uses: actions/download-artifact@v4
          with:
            name: asciify.pr.spdx.json
        - name: Setup Grype
          uses: anchore/scan-action/download-grype@v3
          id: grype
        - name: Analyze SBOM
          run: echo "$(${{steps.grype.outputs.cmd}} sbom:asciify.pr.spdx.json -o table)" >> $GITHUB_OUTPUT
          id: analysis
    comment:
        needs: analyze
        runs-on: ubuntu-latest
        steps:
        - name: Comment on PR
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '${{needs.analyze.outputs.result}}'
              })
